version: '3.8'

services:
  web:
    build: .
    container_name: mx-checker
    ports:
      - "5005:5005"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - mx-network

networks:
  mx-network:
    driver: bridge