apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-rc
    type: front-end

spec:
  replicas: 3
  selector:
    app: my-rc
  template:
    metadata:
      labels:
        app: my-rc
    spec:
      containers:
      - name: my-rc
        image: nginx:1.7.9
        ports:
        - containerPort: 80